version: '3'

services:

  tarantool-node1:
    image: tarantool/tarantool:2.8.2
    container_name: tarantool-node1
    hostname: tarantool-node1
    environment:
      - TARANTOOL_USER_NAME=root
      - TARANTOOL_USER_PASSWORD=root
    command: tarantool /opt/tarantool/xtdb.lua
    networks:
      - net
    ports:
      - "3301:3301"
    volumes:
      # operational data (snapshots, xlogs and vinyl runs)
      - "/tmp/tarantool/data:/var/lib/tarantool"
      # application code
      - "./src/main/tarantool:/opt/tarantool"


networks:
  net:
    driver: bridge
